import uuid
from datetime import datetime

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import TSVECTOR, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.config import get_settings
from app.db.base import Base
from app.models.document import DocumentVersion

EMBEDDING_DIM = get_settings().embedding_dim

# The corpus's language, not the users'. See migration 0006.
TEXT_SEARCH_CONFIG = "english"


class Chunk(Base):
    """A retrievable passage, owned by a *version* rather than a document.

    This is the join that makes both PoC features possible: an audit row records
    chunk ids, and every chunk resolves to an exact edition and page.
    """

    __tablename__ = "chunks"
    __table_args__ = (
        UniqueConstraint("document_version_id", "ordinal", name="uq_chunk_ordinal"),
        CheckConstraint("page_end >= page_start", name="ck_chunk_page_span"),
        # Declared here as well as in migration 0001 so that `alembic check` compares
        # like with like. Without it autogenerate sees an index the models never
        # mention and proposes dropping it — which would make the drift detector cry
        # wolf on every run, and a drift detector nobody trusts gets switched off.
        Index("ix_chunks_content_tsv", "content_tsv", postgresql_using="gin"),
        Index(
            "ix_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    document_version_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("document_versions.id", ondelete="CASCADE"), index=True
    )

    ordinal: Mapped[int] = mapped_column(Integer)  # position within the version

    # A chunk may span a page break, because a page break is typography rather than
    # meaning. Both are 1-based PDF page indices — see app/services/extraction.py on
    # why that is not necessarily the number printed on the page.
    page_start: Mapped[int] = mapped_column(Integer)
    page_end: Mapped[int] = mapped_column(Integer)

    section: Mapped[str | None] = mapped_column(Text)

    content: Mapped[str] = mapped_column(Text)
    embedding: Mapped[list[float]] = mapped_column(Vector(EMBEDDING_DIM))

    # A bibliography entry, not guidance (#50). Set at ingestion by
    # services/references.looks_like_reference, and excluded from retrieval — a reference's
    # paper titles carry clinical keywords and out-rank the guidance that answers a question.
    # Not deleted, only flagged: the chunk is still real text a citation could resolve to.
    is_reference: Mapped[bool] = mapped_column(Boolean, server_default="false", default=False)

    # The chunk that re-read this same printed row better, or NULL while this is the current
    # reading. Excluded from retrieval exactly like is_reference, and for the same reason:
    # the row must stay resolvable for the audit trail (0008 forbids deleting a cited chunk)
    # while no longer competing to answer.
    #
    # Why this exists: augment_tables is insert-only, so every extractor fix lays a corrected
    # row down BESIDE the flawed one and both stay searchable. After the label-completion fix
    # 88 truncated rows sat next to their completed twins, and "ii. Systolic ≥160 mm Hg or"
    # could still out-rank the full threshold — half a criterion, quoted verbatim.
    #
    # A pointer rather than a boolean: it records WHICH row replaced this one, so a pairing
    # can be checked afterwards instead of taken on trust. The rule that sets it is
    # services/row_supersession.replaces, deliberately narrow — mis-pairing silently retires a
    # row nobody would notice was gone.
    superseded_by: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("chunks.id", ondelete="SET NULL"), nullable=True, index=True
    )

    # Generated by Postgres from `content` (migration 0006). Declared read-only here so
    # nothing can write it: a tsvector maintained in application code drifts the first
    # time content changes without it, and a stale lexical index fails by finding
    # nothing rather than by raising.
    content_tsv: Mapped[str] = mapped_column(
        TSVECTOR,
        Computed(f"to_tsvector('{TEXT_SEARCH_CONFIG}', content)", persisted=True),
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    document_version: Mapped[DocumentVersion] = relationship(back_populates="chunks")
