/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/documents/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest a guideline PDF
         * @description Hash, deduplicate, store, register.
         *
         *     Order matters. The bytes are hashed and staged to a temp file before anything
         *     touches the database, so a rejected upload leaves no row behind — and the file only
         *     enters the store once the row is safely committed, so the store never holds a PDF
         *     that no version points at.
         */
        post: operations["create_version_documents_versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{version_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream a version's source PDF
         * @description The original PDF a citation points at, so a clinician can verify us against the
         *     source (#35). Verification a doctor will not actually perform is not verification, so
         *     this exists to make it one click.
         *
         *     **Tenancy is the same one row-level security enforces everywhere, not a second copy of
         *     it.** The file store is content-addressed by hash and has no notion of a clinic — two
         *     clinics that upload the same bytes share one physical file. So access is decided at the
         *     *row*, not the file: this reads the version under `get_tenant_session`, and RLS returns
         *     it only if its document is visible (a published guideline with clinic_id NULL, or this
         *     clinic's own upload). A version another clinic owns is filtered out and reads exactly
         *     like one that does not exist — a 404 either way, so the endpoint never confirms that a
         *     document exists in a clinic the caller cannot see.
         *
         *     The client passes a `version_id`, never a path or hash, so there is nothing to traverse;
         *     the path served is the one the row already holds. `FileResponse` streams from disk and
         *     honours Range requests, so a 100MB guideline never lands in memory and a PDF viewer can
         *     fetch the pages it needs.
         */
        get: operations["get_version_pdf_documents__version_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Query
         * @description Ask the corpus. Recorded against the token's subject.
         *
         *     Every answer is a hash-chained audit row before it is a response body (#26). There is
         *     no unaudited way to query, which is the point of putting the audit inside the pipeline
         *     rather than in this handler: a second endpoint added later cannot forget to call it.
         */
        post: operations["post_query_queries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Erase Query
         * @description Erase one question. Idempotent.
         *
         *     Returns 200 on a query that was already erased rather than 404 or 409: a retried
         *     request must not be able to make a caller think the erasure failed, and the second
         *     call writes no second record.
         */
        delete: operations["erase_query_queries__query_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/translate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Translation
         * @description A reading aid for one quote. Not an answer, not evidence, not audited as either.
         */
        post: operations["post_translation_translate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mint Invite
         * @description Mint an invite for the admin's own clinic. The raw code is in the response once.
         */
        post: operations["mint_invite_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Redeem an invite and create the account it grants. Unauthenticated by necessity — the
         *     code is the gate. Every failure rolls the transaction back, so a code is never spent unless
         *     the account was actually made.
         */
        post: operations["register_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Verify
         * @description Walk the caller's own chain end to end, and checkpoint it if intact.
         *
         *     **The caller's clinic, from the token — there is no "verify everything" here.** Chains
         *     are per clinic (0011), so this is the endpoint a tenant uses to check their own trail,
         *     which is the only chain they can see and the only one they need. Verifying every
         *     clinic is an operator's job and lives in `cli/verify_chain.py`, where it belongs: it
         *     reads across tenants.
         *
         *     **A break returns 500, not 200.** It used to return 200 with `{"intact": false}` in
         *     the body, which is the sort of thing that reads fine and fails in production: every
         *     generic monitor — `curl -f`, an uptime check, a Kubernetes probe, a cron entry that
         *     checks exit status — treats 200 as healthy. Scheduling that endpoint (#29) would have
         *     produced a green dashboard over a rewritten trail. A check that reports its own
         *     failure as success is worse than no check: it manufactures confidence.
         *
         *     500 rather than a 4xx because a broken chain is not the caller's fault, and rather
         *     than 503 because retrying will not help.
         */
        get: operations["audit_verify_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnswerPayload
         * @description Persisted verbatim into audit_log.response.
         */
        AnswerPayload: {
            /** Query Language */
            query_language?: string | null;
            /** Groups */
            groups?: components["schemas"]["SourceGroup"][];
            /** Conflicts */
            conflicts?: components["schemas"]["ConflictFinding"][];
            no_answer_reason?: components["schemas"]["NoAnswerReason"] | null;
            /**
             * Rejected Citations
             * @default 0
             */
            rejected_citations: number;
        };
        /** Body_create_version_documents_versions_post */
        Body_create_version_documents_versions_post: {
            /** File */
            file: string;
            /** Title */
            title: string;
            issuing_org: components["schemas"]["IssuingOrg"];
            /** Version Label */
            version_label: string;
            /** Guideline Type */
            guideline_type?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /**
         * Citation
         * @description A verbatim span of a source, and exactly where it came from.
         *
         *     `quote` is the only clinical text in this schema. Everything else is provenance.
         */
        Citation: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Document Title */
            document_title: string;
            /** Issuing Org */
            issuing_org: string;
            /** Version Label */
            version_label: string;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Section */
            section?: string | null;
            /**
             * Quote
             * @description A contiguous verbatim span of the cited chunk. Never paraphrased, never elided: two separate spans are two citations. Validated by #19 against the chunk text.
             */
            quote: string;
        };
        /**
         * ConflictFinding
         * @description Raised only when retrieval spans multiple issuing organisations and a comparison
         *     pass finds them genuinely divergent.
         *
         *     Divergence is reported, never resolved: we show both passages and let the clinician
         *     judge. Picking a winner would be the advice we are avoiding.
         *
         *     **`description` is model prose and #19 does not validate it** — the same category of
         *     hole that removed `ExtractedStatement.text` above. It survives for now because it
         *     labels a view in which both quotes are the content, rather than replacing them the
         *     way a statement headline did. That is a UI assumption living in a schema, which is
         *     fragile. Settle it at #24, before a prompt is written that fills it.
         */
        ConflictFinding: {
            /** Topic */
            topic: string;
            /** Description */
            description: string;
            /**
             * Conflicting Group Ids
             * @description document_version_ids of the diverging sources
             */
            conflicting_group_ids: string[];
        };
        /** ErasureRequest */
        ErasureRequest: {
            legal_basis: components["schemas"]["LegalBasis"];
        };
        /** ErasureResponse */
        ErasureResponse: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /**
             * Redacted At
             * Format: date-time
             */
            redacted_at: string;
            /** Erased By */
            erased_by: string;
            /**
             * Detail
             * @default question and salt destroyed; the audit row remains and the chain still verifies. Which question was asked can no longer be established by anyone.
             */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteRequest */
        InviteRequest: {
            /** Role */
            role?: string | null;
            /**
             * Ttl Hours
             * @default 72
             */
            ttl_hours: number;
        };
        /** InviteResponse */
        InviteResponse: {
            /** Code */
            code: string;
            /** Clinic Id */
            clinic_id: string;
            /** Role */
            role: string | null;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * IssuingOrg
         * @enum {string}
         */
        IssuingOrg: "ESC" | "AHA" | "ACC" | "WHO" | "NICE" | "NHLBI" | "CDC" | "ADA" | "EASD" | "ESMO" | "ASCO" | "IDSA" | "KDIGO" | "GINA";
        /**
         * LegalBasis
         * @description Why an erasure was performed. An enum, and that is the security control.
         *
         *     A free-text `reason` is where someone writes "erased the question about the enalapril
         *     dose for the patient in bed 4" — re-creating, in an append-only table, the thing that
         *     was just destroyed. The issue calls this the recursion. The fix is not a warning in a
         *     code review; it is that no field exists to hold prose.
         * @enum {string}
         */
        LegalBasis: "consent_withdrawn" | "no_longer_necessary" | "unlawful_processing" | "objection_upheld" | "legal_obligation" | "operator_request";
        /**
         * NoAnswerReason
         * @description Why nothing is being shown — a closed set, not prose.
         *
         *     Free text here would be the same hole that removed `ExtractedStatement.text`: a
         *     model asked to explain itself in an empty answer will write "no guidance found,
         *     though enalapril is generally used" — advice, smuggled through the one field that
         *     was meant to say there is none.
         *
         *     An enum leaves nothing to write into. The wording a clinician reads lives in the UI,
         *     where a human chose it.
         *
         *     The three are kept apart because conflating them tells a clinician the wrong thing.
         *     "The corpus has nothing on this" is a fact about the guidelines. "The answer could
         *     not be verified" is a fact about us malfunctioning — and reporting our own failure as
         *     an absence of guidance would be the quietest lie this system could tell.
         * @enum {string}
         */
        NoAnswerReason: "no_relevant_sources" | "sources_do_not_answer" | "verification_failed" | "table_not_citable";
        /** QueryRequest */
        QueryRequest: {
            /** Question */
            question: string;
            /** Language */
            language?: string | null;
            /**
             * Include Archived
             * @default false
             */
            include_archived: boolean;
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** QueryResponse */
        QueryResponse: {
            /**
             * Query Id
             * Format: uuid
             */
            query_id: string;
            /** Audit Seq */
            audit_seq: number;
            /** Actor Id */
            actor_id: string;
            answer: components["schemas"]["AnswerPayload"];
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Code */
            code: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name?: string | null;
        };
        /** RegisterResponse */
        RegisterResponse: {
            /** User Id */
            user_id: string;
        };
        /**
         * SourceGroup
         * @description What one issuing organisation's guideline says, in its own words.
         *
         *     Grouped by organisation so a clinician sees *whose* guidance they are reading before
         *     they read it — and so #23 can tell whether a result set spans more than one body.
         */
        SourceGroup: {
            /** Issuing Org */
            issuing_org: string;
            /** Version Label */
            version_label: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            /**
             * Is Superseded
             * @default false
             */
            is_superseded: boolean;
            /** Superseding Version Label */
            superseding_version_label?: string | null;
            /** Unreadable Pages */
            unreadable_pages?: number[];
        };
        /** TranslateRequest */
        TranslateRequest: {
            /** Quote */
            quote: string;
            /** Target Language */
            target_language: string;
        };
        /**
         * TranslateResponse
         * @description Machine output, and the field names say so.
         *
         *     `text`, never `quote`: `Citation.quote` means "verbatim and validated" everywhere else in
         *     this system. `is_machine_translation` is always true and exists so a UI cannot render this
         *     without a field telling it what it is.
         */
        TranslateResponse: {
            /** Source Quote */
            source_quote: string;
            /** Target Language */
            target_language: string;
            /** Text */
            text: string;
            /**
             * Is Machine Translation
             * @default true
             */
            is_machine_translation: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCreated */
        VersionCreated: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Title */
            title: string;
            issuing_org: components["schemas"]["IssuingOrg"];
            /** Version Label */
            version_label: string;
            /** File Hash */
            file_hash: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["VersionStatus"];
        };
        /**
         * VersionStatus
         * @enum {string}
         */
        VersionStatus: "pending" | "active" | "archived" | "withdrawn";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_version_documents_versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_version_documents_versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionCreated"];
                };
            };
            /** @description These bytes are already ingested, or the version label is taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Upload exceeds the size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not a PDF */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_pdf_documents__version_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The source PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description No such version, or not visible to this clinic */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_query_queries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_query_queries__query_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErasureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErasureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_translation_translate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranslateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranslateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mint_invite_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    audit_verify_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The chain is broken — the body says where and since when */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
